version: '3.1'

services:
  proxy:
    image: traefik:v2.10
    container_name: proxy
    command:
      - "--certificatesresolvers.resolver.acme.email=certs@forst.dev"
      - "--certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.resolver.acme.tlschallenge=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: mysql:8.2
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      # inits database with the specified schema
      - ./database/:/docker-entrypoint-initdb.d/:ro
      # store data in separate volume
      - db-data:/var/lib/mysql

  app:
    image: ghcr.io/lukasforst/better-stack-task:master
    container_name: app
    environment:
      DB_ADDRESS: "db:3306"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    labels:
      - "traefik.http.routers.be.entrypoints=websecure"
      - "traefik.http.routers.be.tls.certresolver=resolver"
      - "traefik.http.routers.be.tls=true"
      - "traefik.http.services.be.loadbalancer.server.port=80"
      - "traefik.http.routers.fe.rule=Host(`us.forst.dev`)"

volumes:
  db-data:
